services:
    _defaults:
        autowire: true
        autoconfigure: true

    AlexanderA2\PlatformBundle\:
        resource: '../../'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Tests/'